"""Constants for Sandman Doppler Clocks."""

# Base component constants
NAME = "Sandman Doppler"
DOMAIN = "sandman_doppler"

ATTR_DSN = "dsn"
ATTR_BUTTON = "button"
CONF_SUBTYPE = "subtype"

ATTR_DOPPLER_NAME = "doppler_name"

EVENT_BUTTON_PRESSED = f"{DOMAIN}_button_pressed"

# Coordinator data keys. The string values are deliberately identical to the ones
# doppyler==0.0.20 publishes, because every platform reads its state through
# `state_key=ATTR_*` constants. Redefining them here is what lets Phase 3 drop the
# doppyler dependency without touching a single platform.
ATTR_WIFI = "wifi"
ATTR_TIME_MODE = "time_mode"
ATTR_TIMEZONE = "timezone"
ATTR_TIME_OFFSET = "time_offset"
ATTR_USE_COLON = "use_colon"
ATTR_COLON_BLINK = "colon_blink"
ATTR_USE_LEADING_ZERO = "use_leading_zero"
ATTR_USE_FADE_TIME = "use_fade_time"
ATTR_DISPLAY_SECONDS = "display_seconds"
ATTR_VOLUME_LEVEL = "volume_level"
ATTR_SOUND_PRESET = "sound_preset"
ATTR_SOUND_PRESET_MODE = "sound_preset_mode"
ATTR_ALARMS = "alarms"
ATTR_ALARM_SOUNDS = "alarm_sounds"
ATTR_ALEXA_USE_ASCENDING_ALARMS = "alexa_use_ascending_alarms"
ATTR_LIGHT_SENSOR_VALUE = "lightsensor"
ATTR_IS_IN_DAY_MODE = "is_in_day_mode"
ATTR_DAY_TO_NIGHT_TRANSITION_VALUE = "day_to_night_transition_value"
ATTR_NIGHT_TO_DAY_TRANSITION_VALUE = "night_to_day_transition_value"
ATTR_DAY_DISPLAY_BRIGHTNESS = "day_display_brightness"
ATTR_DAY_BUTTON_BRIGHTNESS = "day_button_brightness"
ATTR_NIGHT_DISPLAY_BRIGHTNESS = "night_display_brightness"
ATTR_NIGHT_BUTTON_BRIGHTNESS = "night_button_brightness"
ATTR_SYNC_BUTTON_AND_DISPLAY_BRIGHTNESS = "sync_button_and_display_brightness"
ATTR_SYNC_BUTTON_AND_DISPLAY_COLOR = "sync_button_and_display_color"
ATTR_SYNC_DAY_AND_NIGHT_COLOR = "sync_day_and_night_color"
ATTR_DAY_DISPLAY_COLOR = "day_display_color"
ATTR_DAY_BUTTON_COLOR = "day_button_color"
ATTR_NIGHT_DISPLAY_COLOR = "night_display_color"
ATTR_NIGHT_BUTTON_COLOR = "night_button_color"
ATTR_WEATHER = "weather"
ATTR_WEATHER_WAKE_UP_TIME = "weather_wake_up_time"
ATTR_CONNECTED_TO_ALEXA = "connected_to_alexa"
ATTR_ALEXA_TAP_TO_TALK_TONE_ENABLED = "alexa_tap_to_talk_tone_enabled"
ATTR_ALEXA_WAKE_WORD_TONE_ENABLED = "alexa_wake_word_tone_enabled"
ATTR_SMART_BUTTON_COLOR = "smart_button_color"

SERVICE_SET_WEATHER_LOCATION = "set_weather_location"
SERVICE_ADD_ALARM = "add_alarm"
SERVICE_UPDATE_ALARM = "update_alarm"
SERVICE_DELETE_ALARM = "delete_alarm"
SERVICE_UPDATE_ALARM = "update_alarm"
SERVICE_SET_MAIN_DISPLAY_TEXT = "set_main_display_text"
SERVICE_SET_MINI_DISPLAY_NUMBER = "set_mini_display_number"
SERVICE_SET_RAINBOW_MODE = "set_rainbow_mode"
SERVICE_ACTIVATE_LIGHT_BAR_BLINK = "activate_light_bar_blink"
SERVICE_ACTIVATE_LIGHT_BAR_COMET = "activate_light_bar_comet"
SERVICE_ACTIVATE_LIGHT_BAR_PULSE = "activate_light_bar_pulse"
SERVICE_ACTIVATE_LIGHT_BAR_SET = "activate_light_bar_set"
SERVICE_ACTIVATE_LIGHT_BAR_SET_EACH = "activate_light_bar_set_each"
SERVICE_ACTIVATE_LIGHT_BAR_SWEEP = "activate_light_bar_sweep"
